application: json-stackoverflow
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: json-stackoverflow.py

- url: /reputation.json
  script: json-stackoverflow.py

- url: /widget.js
  script: json-stackoverflow.py
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /.*
  script: not_found.py
